defmodule Temporal.Api.Enums.V1.CommandType do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  @type t ::
          integer
          | :COMMAND_TYPE_UNSPECIFIED
          | :COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK
          | :COMMAND_TYPE_REQUEST_CANCEL_ACTIVITY_TASK
          | :COMMAND_TYPE_START_TIMER
          | :COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION
          | :COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION
          | :COMMAND_TYPE_CANCEL_TIMER
          | :COMMAND_TYPE_CANCEL_WORKFLOW_EXECUTION
          | :COMMAND_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION
          | :COMMAND_TYPE_RECORD_MARKER
          | :COMMAND_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION
          | :COMMAND_TYPE_START_CHILD_WORKFLOW_EXECUTION
          | :COMMAND_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION
          | :COMMAND_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES

  field :COMMAND_TYPE_UNSPECIFIED, 0
  field :COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK, 1
  field :COMMAND_TYPE_REQUEST_CANCEL_ACTIVITY_TASK, 2
  field :COMMAND_TYPE_START_TIMER, 3
  field :COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION, 4
  field :COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION, 5
  field :COMMAND_TYPE_CANCEL_TIMER, 6
  field :COMMAND_TYPE_CANCEL_WORKFLOW_EXECUTION, 7
  field :COMMAND_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION, 8
  field :COMMAND_TYPE_RECORD_MARKER, 9
  field :COMMAND_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION, 10
  field :COMMAND_TYPE_START_CHILD_WORKFLOW_EXECUTION, 11
  field :COMMAND_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION, 12
  field :COMMAND_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES, 13
end
