defmodule Temporal.Api.Enums.V1.EventType do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  @type t ::
          integer
          | :EVENT_TYPE_UNSPECIFIED
          | :EVENT_TYPE_WORKFLOW_EXECUTION_STARTED
          | :EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED
          | :EVENT_TYPE_WORKFLOW_EXECUTION_FAILED
          | :EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT
          | :EVENT_TYPE_WORKFLOW_TASK_SCHEDULED
          | :EVENT_TYPE_WORKFLOW_TASK_STARTED
          | :EVENT_TYPE_WORKFLOW_TASK_COMPLETED
          | :EVENT_TYPE_WORKFLOW_TASK_TIMED_OUT
          | :EVENT_TYPE_WORKFLOW_TASK_FAILED
          | :EVENT_TYPE_ACTIVITY_TASK_SCHEDULED
          | :EVENT_TYPE_ACTIVITY_TASK_STARTED
          | :EVENT_TYPE_ACTIVITY_TASK_COMPLETED
          | :EVENT_TYPE_ACTIVITY_TASK_FAILED
          | :EVENT_TYPE_ACTIVITY_TASK_TIMED_OUT
          | :EVENT_TYPE_ACTIVITY_TASK_CANCEL_REQUESTED
          | :EVENT_TYPE_ACTIVITY_TASK_CANCELED
          | :EVENT_TYPE_TIMER_STARTED
          | :EVENT_TYPE_TIMER_FIRED
          | :EVENT_TYPE_TIMER_CANCELED
          | :EVENT_TYPE_WORKFLOW_EXECUTION_CANCEL_REQUESTED
          | :EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED
          | :EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED
          | :EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED
          | :EVENT_TYPE_EXTERNAL_WORKFLOW_EXECUTION_CANCEL_REQUESTED
          | :EVENT_TYPE_MARKER_RECORDED
          | :EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED
          | :EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED
          | :EVENT_TYPE_WORKFLOW_EXECUTION_CONTINUED_AS_NEW
          | :EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_INITIATED
          | :EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_FAILED
          | :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_STARTED
          | :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_COMPLETED
          | :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_FAILED
          | :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_CANCELED
          | :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_TIMED_OUT
          | :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_TERMINATED
          | :EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED
          | :EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED
          | :EVENT_TYPE_EXTERNAL_WORKFLOW_EXECUTION_SIGNALED
          | :EVENT_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES

  field :EVENT_TYPE_UNSPECIFIED, 0
  field :EVENT_TYPE_WORKFLOW_EXECUTION_STARTED, 1
  field :EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED, 2
  field :EVENT_TYPE_WORKFLOW_EXECUTION_FAILED, 3
  field :EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT, 4
  field :EVENT_TYPE_WORKFLOW_TASK_SCHEDULED, 5
  field :EVENT_TYPE_WORKFLOW_TASK_STARTED, 6
  field :EVENT_TYPE_WORKFLOW_TASK_COMPLETED, 7
  field :EVENT_TYPE_WORKFLOW_TASK_TIMED_OUT, 8
  field :EVENT_TYPE_WORKFLOW_TASK_FAILED, 9
  field :EVENT_TYPE_ACTIVITY_TASK_SCHEDULED, 10
  field :EVENT_TYPE_ACTIVITY_TASK_STARTED, 11
  field :EVENT_TYPE_ACTIVITY_TASK_COMPLETED, 12
  field :EVENT_TYPE_ACTIVITY_TASK_FAILED, 13
  field :EVENT_TYPE_ACTIVITY_TASK_TIMED_OUT, 14
  field :EVENT_TYPE_ACTIVITY_TASK_CANCEL_REQUESTED, 15
  field :EVENT_TYPE_ACTIVITY_TASK_CANCELED, 16
  field :EVENT_TYPE_TIMER_STARTED, 17
  field :EVENT_TYPE_TIMER_FIRED, 18
  field :EVENT_TYPE_TIMER_CANCELED, 19
  field :EVENT_TYPE_WORKFLOW_EXECUTION_CANCEL_REQUESTED, 20
  field :EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED, 21
  field :EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED, 22
  field :EVENT_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED, 23
  field :EVENT_TYPE_EXTERNAL_WORKFLOW_EXECUTION_CANCEL_REQUESTED, 24
  field :EVENT_TYPE_MARKER_RECORDED, 25
  field :EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED, 26
  field :EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED, 27
  field :EVENT_TYPE_WORKFLOW_EXECUTION_CONTINUED_AS_NEW, 28
  field :EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_INITIATED, 29
  field :EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_FAILED, 30
  field :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_STARTED, 31
  field :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_COMPLETED, 32
  field :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_FAILED, 33
  field :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_CANCELED, 34
  field :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_TIMED_OUT, 35
  field :EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_TERMINATED, 36
  field :EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED, 37
  field :EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED, 38
  field :EVENT_TYPE_EXTERNAL_WORKFLOW_EXECUTION_SIGNALED, 39
  field :EVENT_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES, 40
end
