defmodule Temporal.Api.Enums.V1.WorkflowTaskFailedCause do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  @type t ::
          integer
          | :WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED
          | :WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID
          | :WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE
          | :WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND
          | :WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE
          | :WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY
          | :WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID
          | :WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES
          | :WORKFLOW_TASK_FAILED_CAUSE_NON_DETERMINISTIC_ERROR

  field :WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED, 0
  field :WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND, 1
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES, 2
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES, 3
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES, 4
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES, 5
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES, 6
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES, 7
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES, 8
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES, 9
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES, 10
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES, 11
  field :WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID, 12
  field :WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE, 13
  field :WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE, 14
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES, 15
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES, 16
  field :WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND, 17
  field :WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND, 18
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE, 19
  field :WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW, 20
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY, 21
  field :WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID, 22
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES, 23
  field :WORKFLOW_TASK_FAILED_CAUSE_NON_DETERMINISTIC_ERROR, 24
end
defmodule Temporal.Api.Enums.V1.StartChildWorkflowExecutionFailedCause do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  @type t ::
          integer
          | :START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED
          | :START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS

  field :START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED, 0
  field :START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS, 1
end
defmodule Temporal.Api.Enums.V1.CancelExternalWorkflowExecutionFailedCause do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  @type t ::
          integer
          | :CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED
          | :CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND

  field :CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED, 0
  field :CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND, 1
end
defmodule Temporal.Api.Enums.V1.SignalExternalWorkflowExecutionFailedCause do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  @type t ::
          integer
          | :SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED
          | :SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND

  field :SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED, 0
  field :SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND, 1
end
